version: '3.8'

services:
  api:
    build:
      context: './api'
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - 5000:5000
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
